
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  name = "github.com/container-storage-interface/spec"
  version = "1.0.0-rc2"

[[constraint]]
  branch = "master"
  name = "github.com/golang/glog"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.17.0"

[[constraint]]
  name = "k8s.io/kubernetes"
  version = "v1.14.0"

[[override]]
  version = "kubernetes-1.13.0"
  name = "k8s.io/api"

[[override]]
  version = "kubernetes-1.13.0"
  name = "k8s.io/apiserver"

[[override]]
  version = "kubernetes-1.13.0"
  name = "k8s.io/apiextensions-apiserver"

[[override]]
  name = "github.com/Azure/azure-sdk-for-go"
  version = "v21.3.0"